`timescale 1ns/1ps
`default_nettype none
module top (
    input  wire                         i_pcie_ref_clk_n           ,
    input  wire                         i_pcie_ref_clk_p           ,
    input  wire                         i_pcie_rst_n               ,
    input  wire          [  15: 0]      pcie_rxn                   ,
    input  wire          [  15: 0]      pcie_rxp                   ,
    output wire          [  15: 0]      pcie_txn                   ,
    output wire          [  15: 0]      pcie_txp                   ,
    output wire                         DDR4_act_n                 ,
    output wire          [  16: 0]      DDR4_adr                   ,
    output wire          [   1: 0]      DDR4_ba                    ,
    output wire          [   1: 0]      DDR4_bg                    ,
    output wire          [   0: 0]      DDR4_ck_c                  ,
    output wire          [   0: 0]      DDR4_ck_t                  ,
    output wire          [   0: 0]      DDR4_cke                   ,
    output wire          [   1: 0]      DDR4_cs_n                  ,
    inout  wire          [   8: 0]      DDR4_dm_n                  ,
    inout  wire          [  71: 0]      DDR4_dq                    ,
    inout  wire          [   8: 0]      DDR4_dqs_c                 ,
    inout  wire          [   8: 0]      DDR4_dqs_t                 ,
    output wire          [   0: 0]      DDR4_odt                   ,
    output wire                         DDR4_reset_n               ,
    input  wire                         DDR_ref_clk_n              ,
    input  wire                         DDR_ref_clk_p
);
    wire                                sys_clk,sys_clk_gt,axi_aclk,axi_aresetn,ui_clk,ui_rst,calib,calib_axi  ;
    wire                                s_resetn=axi_aresetn&calib_axi,m_resetn=~ui_rst&calib  ;
IBUFDS_GTE4 u_ref (
    .I                                  (i_pcie_ref_clk_p          ),
    .IB                                 (i_pcie_ref_clk_n          ),
    .CEB                                (1'b0                      ),
    .O                                  (sys_clk_gt                ),
    .ODIV2                              (sys_clk                   )
);
xpm_cdc_single #(
    .DEST_SYNC_FF                       (4)                        ,
    .SRC_INPUT_REG                      (0)
) u_calib_cdc (
    .src_clk                            (1'b0                      ),
    .src_in                             (calib                     ),
    .dest_clk                           (axi_aclk                  ),
    .dest_out                           (calib_axi                 )
);

    wire                 [   3: 0]      q_awid,q_bid,q_arid,q_rid,d_awid,d_bid,d_arid,d_rid  ;
    wire                 [  63: 0]      q_awaddr,q_araddr,d_awaddr,d_araddr  ;
    wire                 [  31: 0]      q_awuser,q_aruser          ;
    wire                 [   7: 0]      q_awlen,q_arlen,d_awlen,d_arlen  ;
    wire                 [   2: 0]      q_awsize,q_arsize,q_awprot,q_arprot,d_awsize,d_arsize,d_awprot,d_arprot  ;
    wire                 [   1: 0]      q_awburst,q_arburst,q_bresp,q_rresp,d_awburst,d_arburst,d_bresp,d_rresp  ;
    wire                 [   3: 0]      q_awcache,q_arcache,d_awcache,d_arcache  ;
    wire                 [ 511: 0]      q_wdata,q_rdata,d_wdata,d_rdata  ;
    wire                 [  63: 0]      q_wuser,q_wstrb,d_wstrb    ;
    wire                                q_awvalid,q_awready,q_awlock,q_wlast,q_wvalid,q_wready,q_bvalid,q_bready  ;
    wire                                q_arvalid,q_arready,q_arlock,q_rvalid,q_rready,q_rlast  ;
    wire                                d_awvalid,d_awready,d_awlock,d_wlast,d_wvalid,d_wready,d_bvalid,d_bready  ;
    wire                                d_arvalid,d_arready,d_arlock,d_rvalid,d_rready,d_rlast  ;
    wire                 [  31: 0]      la_awaddr,la_wdata,la_araddr,la_rdata  ;
    wire                 [   3: 0]      la_wstrb                   ;
    wire                 [   2: 0]      la_awprot,la_arprot        ;
    wire                 [   1: 0]      la_bresp,la_rresp          ;
    wire                                la_awvalid,la_awready,la_wvalid,la_wready,la_bvalid,la_bready  ;
    wire                                la_arvalid,la_arready,la_rvalid,la_rready  ;
    wire                 [  39: 0]      ctrl_awaddr,ctrl_araddr    ;
    wire                 [  31: 0]      ctrl_wdata,ctrl_rdata      ;
    wire                 [   3: 0]      ctrl_wstrb                 ;
    wire                 [   2: 0]      ctrl_awprot,ctrl_arprot    ;
    wire                 [   1: 0]      ctrl_bresp,ctrl_rresp      ;
    wire                                ctrl_awvalid,ctrl_awready,ctrl_wvalid,ctrl_wready  ;
    wire                                ctrl_bvalid,ctrl_bready,ctrl_arvalid,ctrl_arready  ;
    wire                                ctrl_rvalid,ctrl_rready    ;

qdma_0 u_qdma (
    .sys_clk                            (sys_clk                   ),
    .sys_clk_gt                         (sys_clk_gt                ),
    .sys_rst_n                          (i_pcie_rst_n              ),
    .user_lnk_up                        (                          ),
    .pci_exp_txp                        (pcie_txp                  ),
    .pci_exp_txn                        (pcie_txn                  ),
    .pci_exp_rxp                        (pcie_rxp                  ),
    .pci_exp_rxn                        (pcie_rxn                  ),
    .axi_aclk                           (axi_aclk                  ),
    .axi_aresetn                        (axi_aresetn               ),
    .usr_irq_in_vld                     (1'b0                      ),
    .usr_irq_in_vec                     (11'd0                     ),
    .usr_irq_in_fnc                     (8'd0                      ),
    .usr_irq_out_ack                    (                          ),
    .usr_irq_out_fail                   (                          ),
    .tm_dsc_sts_vld                     (                          ),
    .tm_dsc_sts_port_id                 (                          ),
    .tm_dsc_sts_qen                     (                          ),
    .tm_dsc_sts_byp                     (                          ),
    .tm_dsc_sts_dir                     (                          ),
    .tm_dsc_sts_mm                      (                          ),
    .tm_dsc_sts_error                   (                          ),
    .tm_dsc_sts_qid                     (                          ),
    .tm_dsc_sts_avl                     (                          ),
    .tm_dsc_sts_qinv                    (                          ),
    .tm_dsc_sts_irq_arm                 (                          ),
    .tm_dsc_sts_rdy                     (1'b1                      ),
    .tm_dsc_sts_pidx                    (                          ),
    .dsc_crdt_in_crdt                   (16'd0                     ),
    .dsc_crdt_in_qid                    (11'd0                     ),
    .dsc_crdt_in_dir                    (1'b0                      ),
    .dsc_crdt_in_fence                  (1'b0                      ),
    .dsc_crdt_in_vld                    (1'b0                      ),
    .dsc_crdt_in_rdy                    (                          ),
    .m_axi_awid                         (q_awid                    ),
    .m_axi_awaddr                       (q_awaddr                  ),
    .m_axi_awuser                       (q_awuser                  ),
    .m_axi_awlen                        (q_awlen                   ),
    .m_axi_awsize                       (q_awsize                  ),
    .m_axi_awburst                      (q_awburst                 ),
    .m_axi_awprot                       (q_awprot                  ),
    .m_axi_awvalid                      (q_awvalid                 ),
    .m_axi_awready                      (q_awready                 ),
    .m_axi_awlock                       (q_awlock                  ),
    .m_axi_awcache                      (q_awcache                 ),
    .m_axi_wdata                        (q_wdata                   ),
    .m_axi_wuser                        (q_wuser                   ),
    .m_axi_wstrb                        (q_wstrb                   ),
    .m_axi_wlast                        (q_wlast                   ),
    .m_axi_wvalid                       (q_wvalid                  ),
    .m_axi_wready                       (q_wready                  ),
    .m_axi_bid                          (q_bid                     ),
    .m_axi_bresp                        (q_bresp                   ),
    .m_axi_bvalid                       (q_bvalid                  ),
    .m_axi_bready                       (q_bready                  ),
    .m_axi_arid                         (q_arid                    ),
    .m_axi_araddr                       (q_araddr                  ),
    .m_axi_aruser                       (q_aruser                  ),
    .m_axi_arlen                        (q_arlen                   ),
    .m_axi_arsize                       (q_arsize                  ),
    .m_axi_arburst                      (q_arburst                 ),
    .m_axi_arprot                       (q_arprot                  ),
    .m_axi_arvalid                      (q_arvalid                 ),
    .m_axi_arready                      (q_arready                 ),
    .m_axi_arlock                       (q_arlock                  ),
    .m_axi_arcache                      (q_arcache                 ),
    .m_axi_rid                          (q_rid                     ),
    .m_axi_rdata                        (q_rdata                   ),
    .m_axi_rresp                        (q_rresp                   ),
    .m_axi_rlast                        (q_rlast                   ),
    .m_axi_rvalid                       (q_rvalid                  ),
    .m_axi_rready                       (q_rready                  ),
    .m_axil_awaddr                      (la_awaddr                 ),
    .m_axil_awuser                      (                          ),
    .m_axil_awprot                      (la_awprot                 ),
    .m_axil_awvalid                     (la_awvalid                ),
    .m_axil_awready                     (la_awready                ),
    .m_axil_wdata                       (la_wdata                  ),
    .m_axil_wstrb                       (la_wstrb                  ),
    .m_axil_wvalid                      (la_wvalid                 ),
    .m_axil_wready                      (la_wready                 ),
    .m_axil_bvalid                      (la_bvalid                 ),
    .m_axil_bresp                       (la_bresp                  ),
    .m_axil_bready                      (la_bready                 ),
    .m_axil_araddr                      (la_araddr                 ),
    .m_axil_aruser                      (                          ),
    .m_axil_arprot                      (la_arprot                 ),
    .m_axil_arvalid                     (la_arvalid                ),
    .m_axil_arready                     (la_arready                ),
    .m_axil_rdata                       (la_rdata                  ),
    .m_axil_rresp                       (la_rresp                  ),
    .m_axil_rvalid                      (la_rvalid                 ),
    .m_axil_rready                      (la_rready                 ),
    .soft_reset_n                       (1'b1                      ),
    .phy_ready                          (                          ),
    .qsts_out_op                        (                          ),
    .qsts_out_data                      (                          ),
    .qsts_out_port_id                   (                          ),
    .qsts_out_qid                       (                          ),
    .qsts_out_vld                       (                          ),
    .qsts_out_rdy                       (1'b1                      )
    );

axi_clock_converter_0 u_cdc (
    .s_axi_aclk                         (axi_aclk                  ),
    .s_axi_aresetn                      (s_resetn                  ),
    .m_axi_aclk                         (ui_clk                    ),
    .m_axi_aresetn                      (m_resetn                  ),
    .s_axi_awid                         (q_awid                    ),
    .s_axi_awaddr                       (q_awaddr                  ),
    .s_axi_awlen                        (q_awlen                   ),
    .s_axi_awsize                       (q_awsize                  ),
    .s_axi_awburst                      (q_awburst                 ),
    .s_axi_awlock                       (q_awlock                  ),
    .s_axi_awcache                      (q_awcache                 ),
    .s_axi_awprot                       (q_awprot                  ),
    .s_axi_awqos                        (4'd0                      ),
    .s_axi_awregion                     (4'd0                      ),
    .s_axi_awuser                       (q_awuser                  ),
    .s_axi_awvalid                      (q_awvalid                 ),
    .s_axi_awready                      (q_awready                 ),
    .s_axi_wdata                        (q_wdata                   ),
    .s_axi_wstrb                        (q_wstrb                   ),
    .s_axi_wlast                        (q_wlast                   ),
    .s_axi_wuser                        (q_wuser                   ),
    .s_axi_wvalid                       (q_wvalid                  ),
    .s_axi_wready                       (q_wready                  ),
    .s_axi_bid                          (q_bid                     ),
    .s_axi_bresp                        (q_bresp                   ),
    .s_axi_bvalid                       (q_bvalid                  ),
    .s_axi_bready                       (q_bready                  ),
    .s_axi_arid                         (q_arid                    ),
    .s_axi_araddr                       (q_araddr                  ),
    .s_axi_arlen                        (q_arlen                   ),
    .s_axi_arsize                       (q_arsize                  ),
    .s_axi_arburst                      (q_arburst                 ),
    .s_axi_arlock                       (q_arlock                  ),
    .s_axi_arcache                      (q_arcache                 ),
    .s_axi_arprot                       (q_arprot                  ),
    .s_axi_arqos                        (4'd0                      ),
    .s_axi_arregion                     (4'd0                      ),
    .s_axi_aruser                       (q_aruser                  ),
    .s_axi_arvalid                      (q_arvalid                 ),
    .s_axi_arready                      (q_arready                 ),
    .s_axi_rid                          (q_rid                     ),
    .s_axi_rdata                        (q_rdata                   ),
    .s_axi_rresp                        (q_rresp                   ),
    .s_axi_rlast                        (q_rlast                   ),
    .s_axi_rvalid                       (q_rvalid                  ),
    .s_axi_rready                       (q_rready                  ),
    .m_axi_awid                         (d_awid                    ),
    .m_axi_awaddr                       (d_awaddr                  ),
    .m_axi_awlen                        (d_awlen                   ),
    .m_axi_awsize                       (d_awsize                  ),
    .m_axi_awburst                      (d_awburst                 ),
    .m_axi_awlock                       (d_awlock                  ),
    .m_axi_awcache                      (d_awcache                 ),
    .m_axi_awprot                       (d_awprot                  ),
    .m_axi_awqos                        (                          ),
    .m_axi_awregion                     (                          ),
    .m_axi_awuser                       (                          ),
    .m_axi_awvalid                      (d_awvalid                 ),
    .m_axi_awready                      (d_awready                 ),
    .m_axi_wdata                        (d_wdata                   ),
    .m_axi_wstrb                        (d_wstrb                   ),
    .m_axi_wlast                        (d_wlast                   ),
    .m_axi_wuser                        (                          ),
    .m_axi_wvalid                       (d_wvalid                  ),
    .m_axi_wready                       (d_wready                  ),
    .m_axi_bid                          (d_bid                     ),
    .m_axi_bresp                        (d_bresp                   ),
    .m_axi_bvalid                       (d_bvalid                  ),
    .m_axi_bready                       (d_bready                  ),
    .m_axi_arid                         (d_arid                    ),
    .m_axi_araddr                       (d_araddr                  ),
    .m_axi_arlen                        (d_arlen                   ),
    .m_axi_arsize                       (d_arsize                  ),
    .m_axi_arburst                      (d_arburst                 ),
    .m_axi_arlock                       (d_arlock                  ),
    .m_axi_arcache                      (d_arcache                 ),
    .m_axi_arprot                       (d_arprot                  ),
    .m_axi_arqos                        (                          ),
    .m_axi_arregion                     (                          ),
    .m_axi_aruser                       (                          ),
    .m_axi_arvalid                      (d_arvalid                 ),
    .m_axi_arready                      (d_arready                 ),
    .m_axi_rid                          (d_rid                     ),
    .m_axi_rdata                        (d_rdata                   ),
    .m_axi_rresp                        (d_rresp                   ),
    .m_axi_rlast                        (d_rlast                   ),
    .m_axi_rvalid                       (d_rvalid                  ),
    .m_axi_rready                       (d_rready                  )
);

ps_subsystem_wrapper u_ps_subsystem (
    .M_AXI_CTRL_araddr                  (ctrl_araddr               ),
    .M_AXI_CTRL_arprot                  (ctrl_arprot               ),
    .M_AXI_CTRL_arready                 (ctrl_arready              ),
    .M_AXI_CTRL_arvalid                 (ctrl_arvalid              ),
    .M_AXI_CTRL_awaddr                  (ctrl_awaddr               ),
    .M_AXI_CTRL_awprot                  (ctrl_awprot               ),
    .M_AXI_CTRL_awready                 (ctrl_awready              ),
    .M_AXI_CTRL_awvalid                 (ctrl_awvalid              ),
    .M_AXI_CTRL_bready                  (ctrl_bready               ),
    .M_AXI_CTRL_bresp                   (ctrl_bresp                ),
    .M_AXI_CTRL_bvalid                  (ctrl_bvalid               ),
    .M_AXI_CTRL_rdata                   (ctrl_rdata                ),
    .M_AXI_CTRL_rready                  (ctrl_rready               ),
    .M_AXI_CTRL_rresp                   (ctrl_rresp                ),
    .M_AXI_CTRL_rvalid                  (ctrl_rvalid               ),
    .M_AXI_CTRL_wdata                   (ctrl_wdata                ),
    .M_AXI_CTRL_wready                  (ctrl_wready               ),
    .M_AXI_CTRL_wstrb                   (ctrl_wstrb                ),
    .M_AXI_CTRL_wvalid                  (ctrl_wvalid               ),
    .S_AXI_HOST_araddr                  ({8'd0,la_araddr}          ),
    .S_AXI_HOST_arprot                  (la_arprot                 ),
    .S_AXI_HOST_arready                 (la_arready                ),
    .S_AXI_HOST_arvalid                 (la_arvalid                ),
    .S_AXI_HOST_awaddr                  ({8'd0,la_awaddr}          ),
    .S_AXI_HOST_awprot                  (la_awprot                 ),
    .S_AXI_HOST_awready                 (la_awready                ),
    .S_AXI_HOST_awvalid                 (la_awvalid                ),
    .S_AXI_HOST_bready                  (la_bready                 ),
    .S_AXI_HOST_bresp                   (la_bresp                  ),
    .S_AXI_HOST_bvalid                  (la_bvalid                 ),
    .S_AXI_HOST_rdata                   (la_rdata                  ),
    .S_AXI_HOST_rready                  (la_rready                 ),
    .S_AXI_HOST_rresp                   (la_rresp                  ),
    .S_AXI_HOST_rvalid                  (la_rvalid                 ),
    .S_AXI_HOST_wdata                   (la_wdata                  ),
    .S_AXI_HOST_wready                  (la_wready                 ),
    .S_AXI_HOST_wstrb                   (la_wstrb                  ),
    .S_AXI_HOST_wvalid                  (la_wvalid                 ),
    .ctrl_aclk                          (axi_aclk                  ),
    .ctrl_aresetn                       (axi_aresetn               ),
    .ps_irq                             (1'b0                      ),
    .ps_pl_clk0                         (                          ),
    .ps_pl_clk1                         (                          ),
    .ps_pl_clk2                         (                          ),
    .ps_pl_resetn                       (                          )
);

axi_lite_status u_regs (
    .aclk                               (axi_aclk                  ),
    .aresetn                            (axi_aresetn               ),
    .ddr_calib_done                     (calib_axi                 ),
    .s_awaddr                           (ctrl_awaddr[11:0]         ),
    .s_awvalid                          (ctrl_awvalid              ),
    .s_awready                          (ctrl_awready              ),
    .s_wdata                            (ctrl_wdata                ),
    .s_wstrb                            (ctrl_wstrb                ),
    .s_wvalid                           (ctrl_wvalid               ),
    .s_wready                           (ctrl_wready               ),
    .s_bresp                            (ctrl_bresp                ),
    .s_bvalid                           (ctrl_bvalid               ),
    .s_bready                           (ctrl_bready               ),
    .s_araddr                           (ctrl_araddr[11:0]         ),
    .s_arvalid                          (ctrl_arvalid              ),
    .s_arready                          (ctrl_arready              ),
    .s_rdata                            (ctrl_rdata                ),
    .s_rresp                            (ctrl_rresp                ),
    .s_rvalid                           (ctrl_rvalid               ),
    .s_rready                           (ctrl_rready               )
);

ddr4_0 u_ddr (
    .sys_rst                            (~i_pcie_rst_n             ),
    .c0_sys_clk_p                       (DDR_ref_clk_p             ),
    .c0_sys_clk_n                       (DDR_ref_clk_n             ),
    .c0_ddr4_act_n                      (DDR4_act_n                ),
    .c0_ddr4_adr                        (DDR4_adr                  ),
    .c0_ddr4_ba                         (DDR4_ba                   ),
    .c0_ddr4_bg                         (DDR4_bg                   ),
    .c0_ddr4_cke                        (DDR4_cke                  ),
    .c0_ddr4_odt                        (DDR4_odt                  ),
    .c0_ddr4_cs_n                       (DDR4_cs_n                 ),
    .c0_ddr4_ck_t                       (DDR4_ck_t                 ),
    .c0_ddr4_ck_c                       (DDR4_ck_c                 ),
    .c0_ddr4_reset_n                    (DDR4_reset_n              ),
    .c0_ddr4_dm_dbi_n                   (DDR4_dm_n                 ),
    .c0_ddr4_dq                         (DDR4_dq                   ),
    .c0_ddr4_dqs_c                      (DDR4_dqs_c                ),
    .c0_ddr4_dqs_t                      (DDR4_dqs_t                ),
    .c0_init_calib_complete             (calib                     ),
    .c0_ddr4_ui_clk                     (ui_clk                    ),
    .c0_ddr4_ui_clk_sync_rst            (ui_rst                    ),
    .dbg_clk                            (                          ),
    .dbg_bus                            (                          ),
    .c0_ddr4_aresetn                    (m_resetn                  ),
    .c0_ddr4_interrupt                  (                          ),
    .c0_ddr4_s_axi_ctrl_awvalid         (1'b0                      ),
    .c0_ddr4_s_axi_ctrl_awaddr          (32'd0                     ),
    .c0_ddr4_s_axi_ctrl_awready         (                          ),
    .c0_ddr4_s_axi_ctrl_wvalid          (1'b0                      ),
    .c0_ddr4_s_axi_ctrl_wdata           (32'd0                     ),
    .c0_ddr4_s_axi_ctrl_wready          (                          ),
    .c0_ddr4_s_axi_ctrl_bvalid          (                          ),
    .c0_ddr4_s_axi_ctrl_bready          (1'b1                      ),
    .c0_ddr4_s_axi_ctrl_bresp           (                          ),
    .c0_ddr4_s_axi_ctrl_arvalid         (1'b0                      ),
    .c0_ddr4_s_axi_ctrl_araddr          (32'd0                     ),
    .c0_ddr4_s_axi_ctrl_arready         (                          ),
    .c0_ddr4_s_axi_ctrl_rvalid          (                          ),
    .c0_ddr4_s_axi_ctrl_rready          (1'b1                      ),
    .c0_ddr4_s_axi_ctrl_rdata           (                          ),
    .c0_ddr4_s_axi_ctrl_rresp           (                          ),
    .c0_ddr4_s_axi_awid                 (d_awid                    ),
    .c0_ddr4_s_axi_awaddr               (d_awaddr[32:0]            ),
    .c0_ddr4_s_axi_awlen                (d_awlen                   ),
    .c0_ddr4_s_axi_awsize               (d_awsize                  ),
    .c0_ddr4_s_axi_awburst              (d_awburst                 ),
    .c0_ddr4_s_axi_awlock               (d_awlock                  ),
    .c0_ddr4_s_axi_awcache              (d_awcache                 ),
    .c0_ddr4_s_axi_awprot               (d_awprot                  ),
    .c0_ddr4_s_axi_awqos                (4'd0                      ),
    .c0_ddr4_s_axi_awvalid              (d_awvalid                 ),
    .c0_ddr4_s_axi_awready              (d_awready                 ),
    .c0_ddr4_s_axi_wdata                (d_wdata                   ),
    .c0_ddr4_s_axi_wstrb                (d_wstrb                   ),
    .c0_ddr4_s_axi_wlast                (d_wlast                   ),
    .c0_ddr4_s_axi_wvalid               (d_wvalid                  ),
    .c0_ddr4_s_axi_wready               (d_wready                  ),
    .c0_ddr4_s_axi_bready               (d_bready                  ),
    .c0_ddr4_s_axi_bid                  (d_bid                     ),
    .c0_ddr4_s_axi_bresp                (d_bresp                   ),
    .c0_ddr4_s_axi_bvalid               (d_bvalid                  ),
    .c0_ddr4_s_axi_arid                 (d_arid                    ),
    .c0_ddr4_s_axi_araddr               (d_araddr[32:0]            ),
    .c0_ddr4_s_axi_arlen                (d_arlen                   ),
    .c0_ddr4_s_axi_arsize               (d_arsize                  ),
    .c0_ddr4_s_axi_arburst              (d_arburst                 ),
    .c0_ddr4_s_axi_arlock               (d_arlock                  ),
    .c0_ddr4_s_axi_arcache              (d_arcache                 ),
    .c0_ddr4_s_axi_arprot               (d_arprot                  ),
    .c0_ddr4_s_axi_arqos                (4'd0                      ),
    .c0_ddr4_s_axi_arvalid              (d_arvalid                 ),
    .c0_ddr4_s_axi_arready              (d_arready                 ),
    .c0_ddr4_s_axi_rready               (d_rready                  ),
    .c0_ddr4_s_axi_rid                  (d_rid                     ),
    .c0_ddr4_s_axi_rdata                (d_rdata                   ),
    .c0_ddr4_s_axi_rresp                (d_rresp                   ),
    .c0_ddr4_s_axi_rlast                (d_rlast                   ),
    .c0_ddr4_s_axi_rvalid               (d_rvalid                  )
);
endmodule
`default_nettype wire
