###################################
############ pcie x16 #############
###################################
create_clock -period 10.0 -name pcie_ref_clk [get_ports i_pcie_ref_clk_p]

set_property PACKAGE_PIN AF11 [get_ports i_pcie_ref_clk_n]
set_property PACKAGE_PIN AF12 [get_ports i_pcie_ref_clk_p]

set_property PACKAGE_PIN L13 [get_ports i_pcie_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports i_pcie_rst_n]
set_property PULLUP true [get_ports i_pcie_rst_n]

# set_property PACKAGE_PIN F12 [get_ports DDR_rst_n]
# set_property IOSTANDARD LVCMOS33 [get_ports DDR_rst_n]
# set_property PULLUP true [get_ports DDR_rst_n]

#tx
#rx                      000
set_property PACKAGE_PIN BA2 [get_ports {pcie_rxp[15]}]
set_property PACKAGE_PIN BA1 [get_ports {pcie_rxn[15]}]
set_property PACKAGE_PIN AY4 [get_ports {pcie_txp[15]}]
set_property PACKAGE_PIN AY3 [get_ports {pcie_txn[15]}]
set_property PACKAGE_PIN AW2 [get_ports {pcie_rxp[14]}]
set_property PACKAGE_PIN AW1 [get_ports {pcie_rxn[14]}]
set_property PACKAGE_PIN AW6 [get_ports {pcie_txp[14]}]
set_property PACKAGE_PIN AW5 [get_ports {pcie_txn[14]}]
set_property PACKAGE_PIN AV4 [get_ports {pcie_rxp[13]}]
set_property PACKAGE_PIN AV3 [get_ports {pcie_rxn[13]}]
set_property PACKAGE_PIN AU6 [get_ports {pcie_txp[13]}]
set_property PACKAGE_PIN AU5 [get_ports {pcie_txn[13]}]
set_property PACKAGE_PIN AU2 [get_ports {pcie_rxp[12]}]
set_property PACKAGE_PIN AU1 [get_ports {pcie_rxn[12]}]
set_property PACKAGE_PIN AT8 [get_ports {pcie_txp[12]}]
set_property PACKAGE_PIN AT7 [get_ports {pcie_txn[12]}]
set_property PACKAGE_PIN AT4 [get_ports {pcie_rxp[11]}]
set_property PACKAGE_PIN AT3 [get_ports {pcie_rxn[11]}]
set_property PACKAGE_PIN AR6 [get_ports {pcie_txp[11]}]
set_property PACKAGE_PIN AR5 [get_ports {pcie_txn[11]}]
set_property PACKAGE_PIN AR2 [get_ports {pcie_rxp[10]}]
set_property PACKAGE_PIN AR1 [get_ports {pcie_rxn[10]}]
set_property PACKAGE_PIN AP8 [get_ports {pcie_txp[10]}]
set_property PACKAGE_PIN AP7 [get_ports {pcie_txn[10]}]
set_property PACKAGE_PIN AP4 [get_ports {pcie_rxp[9]}]
set_property PACKAGE_PIN AP3 [get_ports {pcie_rxn[9]}]
set_property PACKAGE_PIN AN6 [get_ports {pcie_txp[9]}]
set_property PACKAGE_PIN AN5 [get_ports {pcie_txn[9]}]
set_property PACKAGE_PIN AN2 [get_ports {pcie_rxp[8]}]
set_property PACKAGE_PIN AN1 [get_ports {pcie_rxn[8]}]
set_property PACKAGE_PIN AM8 [get_ports {pcie_txp[8]}]
set_property PACKAGE_PIN AM7 [get_ports {pcie_txn[8]}]
set_property PACKAGE_PIN AM4 [get_ports {pcie_rxp[7]}]
set_property PACKAGE_PIN AM3 [get_ports {pcie_rxn[7]}]
set_property PACKAGE_PIN AL6 [get_ports {pcie_txp[7]}]
set_property PACKAGE_PIN AL5 [get_ports {pcie_txn[7]}]
set_property PACKAGE_PIN AL2 [get_ports {pcie_rxp[6]}]
set_property PACKAGE_PIN AL1 [get_ports {pcie_rxn[6]}]
set_property PACKAGE_PIN AK8 [get_ports {pcie_txp[6]}]
set_property PACKAGE_PIN AK7 [get_ports {pcie_txn[6]}]
set_property PACKAGE_PIN AK4 [get_ports {pcie_rxp[5]}]
set_property PACKAGE_PIN AK3 [get_ports {pcie_rxn[5]}]
set_property PACKAGE_PIN AJ6 [get_ports {pcie_txp[5]}]
set_property PACKAGE_PIN AJ5 [get_ports {pcie_txn[5]}]
set_property PACKAGE_PIN AJ2 [get_ports {pcie_rxp[4]}]
set_property PACKAGE_PIN AJ1 [get_ports {pcie_rxn[4]}]
set_property PACKAGE_PIN AH8 [get_ports {pcie_txp[4]}]
set_property PACKAGE_PIN AH7 [get_ports {pcie_txn[4]}]
set_property PACKAGE_PIN AH4 [get_ports {pcie_rxp[3]}]
set_property PACKAGE_PIN AH3 [get_ports {pcie_rxn[3]}]
set_property PACKAGE_PIN AG6 [get_ports {pcie_txp[3]}]
set_property PACKAGE_PIN AG5 [get_ports {pcie_txn[3]}]
set_property PACKAGE_PIN AG2 [get_ports {pcie_rxp[2]}]
set_property PACKAGE_PIN AG1 [get_ports {pcie_rxn[2]}]
set_property PACKAGE_PIN AF8 [get_ports {pcie_txp[2]}]
set_property PACKAGE_PIN AF7 [get_ports {pcie_txn[2]}]
set_property PACKAGE_PIN AF4 [get_ports {pcie_rxp[1]}]
set_property PACKAGE_PIN AF3 [get_ports {pcie_rxn[1]}]
set_property PACKAGE_PIN AE6 [get_ports {pcie_txp[1]}]
set_property PACKAGE_PIN AE5 [get_ports {pcie_txn[1]}]
set_property PACKAGE_PIN AE2 [get_ports {pcie_rxp[0]}]
set_property PACKAGE_PIN AE1 [get_ports {pcie_rxn[0]}]
set_property PACKAGE_PIN AD8 [get_ports {pcie_txp[0]}]
set_property PACKAGE_PIN AD7 [get_ports {pcie_txn[0]}]
###################################
############ PL-DDR4 #############
###################################
#       address
set_property PACKAGE_PIN K29 [get_ports {DDR4_adr[0]}]
set_property PACKAGE_PIN J29 [get_ports {DDR4_adr[1]}]
set_property PACKAGE_PIN J30 [get_ports {DDR4_adr[2]}]
set_property PACKAGE_PIN H30 [get_ports {DDR4_adr[3]}]
set_property PACKAGE_PIN F31 [get_ports {DDR4_adr[4]}]
set_property PACKAGE_PIN F32 [get_ports {DDR4_adr[5]}]
set_property PACKAGE_PIN G30 [get_ports {DDR4_adr[6]}]
set_property PACKAGE_PIN F30 [get_ports {DDR4_adr[7]}]
set_property PACKAGE_PIN G28 [get_ports {DDR4_adr[8]}]
set_property PACKAGE_PIN F29 [get_ports {DDR4_adr[9]}]
set_property PACKAGE_PIN J28 [get_ports {DDR4_adr[10]}]
set_property PACKAGE_PIN H28 [get_ports {DDR4_adr[11]}]
set_property PACKAGE_PIN E29 [get_ports {DDR4_adr[12]}]
set_property PACKAGE_PIN D29 [get_ports {DDR4_adr[13]}]
set_property PACKAGE_PIN C29 [get_ports {DDR4_adr[14]}]
set_property PACKAGE_PIN B30 [get_ports {DDR4_adr[15]}]
set_property PACKAGE_PIN A29 [get_ports {DDR4_adr[16]}]

#       data (72-bit physical interface: 64-bit data + 8-bit ECC)
set_property PACKAGE_PIN G26 [get_ports {DDR4_dm_n[0]}]
set_property PACKAGE_PIN E26 [get_ports {DDR4_dqs_t[0]}]
set_property PACKAGE_PIN E27 [get_ports {DDR4_dqs_c[0]}]
set_property PACKAGE_PIN D27 [get_ports {DDR4_dq[0]}]
set_property PACKAGE_PIN D28 [get_ports {DDR4_dq[1]}]
set_property PACKAGE_PIN F25 [get_ports {DDR4_dq[2]}]
set_property PACKAGE_PIN E25 [get_ports {DDR4_dq[3]}]
set_property PACKAGE_PIN F27 [get_ports {DDR4_dq[4]}]
set_property PACKAGE_PIN F28 [get_ports {DDR4_dq[5]}]
set_property PACKAGE_PIN F24 [get_ports {DDR4_dq[6]}]
set_property PACKAGE_PIN E24 [get_ports {DDR4_dq[7]}]
set_property PACKAGE_PIN C28 [get_ports {DDR4_dm_n[1]}]
set_property PACKAGE_PIN B25 [get_ports {DDR4_dqs_t[1]}]
set_property PACKAGE_PIN B26 [get_ports {DDR4_dqs_c[1]}]
set_property PACKAGE_PIN C24 [get_ports {DDR4_dq[8]}]
set_property PACKAGE_PIN C25 [get_ports {DDR4_dq[9]}]
set_property PACKAGE_PIN A24 [get_ports {DDR4_dq[10]}]
set_property PACKAGE_PIN A25 [get_ports {DDR4_dq[11]}]
set_property PACKAGE_PIN C26 [get_ports {DDR4_dq[12]}]
set_property PACKAGE_PIN B27 [get_ports {DDR4_dq[13]}]
set_property PACKAGE_PIN A27 [get_ports {DDR4_dq[14]}]
set_property PACKAGE_PIN A28 [get_ports {DDR4_dq[15]}]
set_property PACKAGE_PIN P26 [get_ports {DDR4_dm_n[2]}]
set_property PACKAGE_PIN L24 [get_ports {DDR4_dqs_t[2]}]
set_property PACKAGE_PIN K24 [get_ports {DDR4_dqs_c[2]}]
set_property PACKAGE_PIN P23 [get_ports {DDR4_dq[16]}]
set_property PACKAGE_PIN N23 [get_ports {DDR4_dq[17]}]
set_property PACKAGE_PIN M25 [get_ports {DDR4_dq[18]}]
set_property PACKAGE_PIN L25 [get_ports {DDR4_dq[19]}]
set_property PACKAGE_PIN N24 [get_ports {DDR4_dq[20]}]
set_property PACKAGE_PIN N25 [get_ports {DDR4_dq[21]}]
set_property PACKAGE_PIN M23 [get_ports {DDR4_dq[22]}]
set_property PACKAGE_PIN L23 [get_ports {DDR4_dq[23]}]
set_property PACKAGE_PIN K27 [get_ports {DDR4_dm_n[3]}]
set_property PACKAGE_PIN H23 [get_ports {DDR4_dqs_t[3]}]
set_property PACKAGE_PIN G23 [get_ports {DDR4_dqs_c[3]}]
set_property PACKAGE_PIN H25 [get_ports {DDR4_dq[24]}]
set_property PACKAGE_PIN H26 [get_ports {DDR4_dq[25]}]
set_property PACKAGE_PIN H24 [get_ports {DDR4_dq[26]}]
set_property PACKAGE_PIN G25 [get_ports {DDR4_dq[27]}]
set_property PACKAGE_PIN J23 [get_ports {DDR4_dq[28]}]
set_property PACKAGE_PIN J24 [get_ports {DDR4_dq[29]}]
set_property PACKAGE_PIN K26 [get_ports {DDR4_dq[30]}]
set_property PACKAGE_PIN J26 [get_ports {DDR4_dq[31]}]
set_property PACKAGE_PIN G22 [get_ports {DDR4_dm_n[4]}]
set_property PACKAGE_PIN F20 [get_ports {DDR4_dqs_t[4]}]
set_property PACKAGE_PIN E20 [get_ports {DDR4_dqs_c[4]}]
set_property PACKAGE_PIN E21 [get_ports {DDR4_dq[32]}]
set_property PACKAGE_PIN D21 [get_ports {DDR4_dq[33]}]
set_property PACKAGE_PIN F23 [get_ports {DDR4_dq[34]}]
set_property PACKAGE_PIN F22 [get_ports {DDR4_dq[35]}]
set_property PACKAGE_PIN F19 [get_ports {DDR4_dq[36]}]
set_property PACKAGE_PIN E19 [get_ports {DDR4_dq[37]}]
set_property PACKAGE_PIN E22 [get_ports {DDR4_dq[38]}]
set_property PACKAGE_PIN D22 [get_ports {DDR4_dq[39]}]
set_property PACKAGE_PIN D19 [get_ports {DDR4_dm_n[5]}]
set_property PACKAGE_PIN C21 [get_ports {DDR4_dqs_t[5]}]
set_property PACKAGE_PIN B21 [get_ports {DDR4_dqs_c[5]}]
set_property PACKAGE_PIN B22 [get_ports {DDR4_dq[40]}]
set_property PACKAGE_PIN A22 [get_ports {DDR4_dq[41]}]
set_property PACKAGE_PIN B23 [get_ports {DDR4_dq[42]}]
set_property PACKAGE_PIN A23 [get_ports {DDR4_dq[43]}]
set_property PACKAGE_PIN A20 [get_ports {DDR4_dq[44]}]
set_property PACKAGE_PIN A19 [get_ports {DDR4_dq[45]}]
set_property PACKAGE_PIN C20 [get_ports {DDR4_dq[46]}]
set_property PACKAGE_PIN B20 [get_ports {DDR4_dq[47]}]
set_property PACKAGE_PIN F14 [get_ports {DDR4_dm_n[6]}]
set_property PACKAGE_PIN B13 [get_ports {DDR4_dqs_t[6]}]
set_property PACKAGE_PIN A12 [get_ports {DDR4_dqs_c[6]}]
set_property PACKAGE_PIN A14 [get_ports {DDR4_dq[48]}]
set_property PACKAGE_PIN A13 [get_ports {DDR4_dq[49]}]
set_property PACKAGE_PIN E15 [get_ports {DDR4_dq[50]}]
set_property PACKAGE_PIN D14 [get_ports {DDR4_dq[51]}]
set_property PACKAGE_PIN D13 [get_ports {DDR4_dq[52]}]
set_property PACKAGE_PIN C13 [get_ports {DDR4_dq[53]}]
set_property PACKAGE_PIN C15 [get_ports {DDR4_dq[54]}]
set_property PACKAGE_PIN B15 [get_ports {DDR4_dq[55]}]
set_property PACKAGE_PIN E16 [get_ports {DDR4_dm_n[7]}]
set_property PACKAGE_PIN B17 [get_ports {DDR4_dqs_t[7]}]
set_property PACKAGE_PIN A17 [get_ports {DDR4_dqs_c[7]}]
set_property PACKAGE_PIN C16 [get_ports {DDR4_dq[56]}]
set_property PACKAGE_PIN B16 [get_ports {DDR4_dq[57]}]
set_property PACKAGE_PIN E17 [get_ports {DDR4_dq[58]}]
set_property PACKAGE_PIN D17 [get_ports {DDR4_dq[59]}]
set_property PACKAGE_PIN D18 [get_ports {DDR4_dq[60]}]
set_property PACKAGE_PIN C18 [get_ports {DDR4_dq[61]}]
set_property PACKAGE_PIN B18 [get_ports {DDR4_dq[62]}]
set_property PACKAGE_PIN A18 [get_ports {DDR4_dq[63]}]

#       ECC byte lane
set_property PACKAGE_PIN P15 [get_ports {DDR4_dm_n[8]}]
set_property PACKAGE_PIN M15 [get_ports {DDR4_dqs_t[8]}]
set_property PACKAGE_PIN L15 [get_ports {DDR4_dqs_c[8]}]
set_property PACKAGE_PIN K17 [get_ports {DDR4_dq[64]}]
set_property PACKAGE_PIN K16 [get_ports {DDR4_dq[65]}]
set_property PACKAGE_PIN P16 [get_ports {DDR4_dq[66]}]
set_property PACKAGE_PIN N16 [get_ports {DDR4_dq[67]}]
set_property PACKAGE_PIN M17 [get_ports {DDR4_dq[68]}]
set_property PACKAGE_PIN M16 [get_ports {DDR4_dq[69]}]
set_property PACKAGE_PIN K15 [get_ports {DDR4_dq[70]}]
set_property PACKAGE_PIN L17 [get_ports {DDR4_dq[71]}]

#    control
set_property PACKAGE_PIN B31 [get_ports {DDR4_ck_t[0]}]
set_property PACKAGE_PIN A32 [get_ports {DDR4_ck_c[0]}]
set_property PACKAGE_PIN C36 [get_ports {DDR4_cke[0]}]
set_property PACKAGE_PIN A38 [get_ports {DDR4_cs_n[1]}]
set_property PACKAGE_PIN B37 [get_ports {DDR4_cs_n[0]}]
set_property PACKAGE_PIN A37 [get_ports DDR4_reset_n]
set_property PACKAGE_PIN B36 [get_ports DDR4_act_n]
set_property PACKAGE_PIN A33 [get_ports {DDR4_ba[0]}]
set_property PACKAGE_PIN A34 [get_ports {DDR4_ba[1]}]
set_property PACKAGE_PIN B35 [get_ports {DDR4_bg[0]}]
set_property PACKAGE_PIN A35 [get_ports {DDR4_bg[1]}]
set_property PACKAGE_PIN C37 [get_ports {DDR4_odt[0]}]

#    system clock
set_property PACKAGE_PIN E32 [get_ports DDR_ref_clk_p]
set_property PACKAGE_PIN D32 [get_ports DDR_ref_clk_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports DDR_ref_clk_*]
